// auto-generated by build_room.py — do not hand-edit
window.LONGVIEW = {
  "moments": [
    {
      "date": "2026-06-24",
      "kind": "receipt",
      "tag": "responsive",
      "title": "felt-sense / data match",
      "body": "heavy-heart feeling before bed + RHR new high (yesterday's) = body and hardware agreeing. Good instrument check, not a disconnect."
    },
    {
      "date": "2026-06-24",
      "kind": "context",
      "tag": "growth",
      "title": "how you came in",
      "body": "HRV 34 (low for her, baseline ~57), RHR 63 (yesterday's value = new logged high, +7 over 7-day avg). Felt fine, lightly tired. Noticed a 'heavy heart' feeling before bed — felt-sense matched the data. Gyno checkup: cysts look back to normal on ultrasound (full results pending). Weekend was socially 'on' both days (Sat birthday, Sun Father's Day), then trained Mon (deload upper) + Tue (hard lower+core). Today is the first low-stimulation day in ~a week."
    },
    {
      "date": "2026-06-23",
      "kind": "receipt",
      "tag": "strength",
      "title": "progression-ready",
      "body": "hip_thrust 70x15x3 under fatigue (2nd 'fired up' in a row) + squats steady at 40 — several lifts ready to move up. Greenlit on a HIGH day."
    },
    {
      "date": "2026-06-23",
      "kind": "context",
      "tag": "growth",
      "title": "how you came in",
      "body": "Trained mid-morning (~9:47am treadmill, ~9:58 strength, ~10:28 core). Felt overall fine at snapshot. Clean HIGH readiness day."
    },
    {
      "date": "2026-06-22",
      "kind": "receipt",
      "tag": "responsive",
      "title": "body-led autonomy",
      "body": "trained on a 33 HRV by checking in every round and letting her body call each one — kept going when good, stopped at R3 when arms were done. Exactly the self-regulation we want. Went fine, no crash."
    },
    {
      "date": "2026-06-22",
      "kind": "receipt",
      "tag": "alive",
      "title": "flow state for fun",
      "body": "post-meeting, unprompted, uncounted floor movement -> flow state. The present/alive self showing up on its own. This is the north star, not a side note."
    },
    {
      "date": "2026-06-22",
      "kind": "context",
      "tag": "growth",
      "title": "how you came in",
      "body": "Two social weekend days (Sat: mom's friend's birthday; Sun: Father's Day with bf's parents). Both fun but 'on' both days. Monday: kinda tired, woke wanting more sleep despite 8.5hr. Trained mid-morning (~10:01-10:58am)."
    },
    {
      "date": "2026-06-19",
      "kind": "receipt",
      "tag": "alive",
      "title": "let real life count",
      "body": "on a LOW-readiness morning she let a ~75min walk built into her actual day BE the cardio — no forcing the run, no piling on extra. Movement folded into living, exactly the point."
    },
    {
      "date": "2026-06-19",
      "kind": "receipt",
      "tag": "responsive",
      "title": "read the body right",
      "body": "HRV -4SD + RHR up the morning after a hard circuit = recovery cost, and she chose the easy walk over the spike. Recovery honored, not overridden."
    },
    {
      "date": "2026-06-19",
      "kind": "context",
      "tag": "growth",
      "title": "how you came in",
      "body": "HRV dropped to 39 (felt chill though), RHR up to 60, slept ~10hr and was 'knocked.' Legs felt good, everything fine. Day-after a hard circuit (peak 183). Had a gyno appointment with a ~30min walk each way built into the day."
    },
    {
      "date": "2026-06-18",
      "kind": "receipt",
      "tag": "strength",
      "title": "clean under fatigue",
      "body": "goblet + sumo squat 40 → 12/12/12 every round, zero drop-off. Legs ready — 45 test greenlit for Monday."
    },
    {
      "date": "2026-06-18",
      "kind": "receipt",
      "tag": "strength",
      "title": "grit at the ceiling",
      "body": "lat pulldown 75 — arms went jello, almost dropped at 7 in the last round, ground it out to 8 anyway. Refused to quit at your top weight."
    },
    {
      "date": "2026-06-18",
      "kind": "context",
      "tag": "growth",
      "title": "how you came in",
      "body": "Feeling fine, just tired. Very slight right-side headache — only noticeable when not occupied, not while training. Trained mid-morning (10:03-10:56am)."
    },
    {
      "date": "2026-06-17",
      "kind": "receipt",
      "tag": "alive",
      "title": "downshift day",
      "body": "clean Zone 2 (avg 107 / peak 121), kept HR boring as planned — parasympathetic counterweight midweek."
    },
    {
      "date": "2026-06-17",
      "kind": "knowing",
      "tag": "alive",
      "title": "you let it be easy on purpose",
      "body": "a clean Zone 2 walk with Chris — and you kept it boring on *purpose*. old you would've chased the burn. choosing the downshift is a skill, and you used it."
    },
    {
      "date": "2026-06-16",
      "kind": "receipt",
      "tag": "strength",
      "title": "squats 40 confirmed (fresh legs)",
      "body": "sumo 12/12/12 clean, goblet 12/12/(8 rushed for meeting). Build-reps met. QUEUE 45 next fresh lower day — she HAS 45lb DBs."
    },
    {
      "date": "2026-06-16",
      "kind": "receipt",
      "tag": "alive",
      "title": "regulation win",
      "body": "handled a 172+ audience presentation confidently (knew the content). Nervous-system-under-pressure receipt, beyond training."
    },
    {
      "date": "2026-06-16",
      "kind": "strength",
      "tag": "strength",
      "title": "stronger than last time",
      "body": "hip thrust: 50 lb (mislabeled, plates-only) → 70 lb (20lb bar + 25x2)"
    },
    {
      "date": "2026-06-16",
      "kind": "responsive",
      "tag": "responsive",
      "title": "a responsive body",
      "body": "HRV 140 — your nervous system voting 'i'm here, i answer.'"
    },
    {
      "date": "2026-06-16",
      "kind": "knowing",
      "tag": "alive",
      "title": "you held a room of 172",
      "body": "gave the presentation, handled the whole room, walked out knowing you handled it. nervous-system-under-pressure, and you stayed regulated. that's the strong you showing up somewhere that isn't the gym."
    },
    {
      "date": "2026-06-15",
      "kind": "receipt",
      "tag": "strength",
      "title": "chest press 50 = progression candidate",
      "body": "12/12/12 'easy,' barely taxed. Bump next chest day."
    },
    {
      "date": "2026-06-15",
      "kind": "receipt",
      "tag": "growth",
      "title": "tricep dip 20 = progression candidate",
      "body": "12/12/12 clean 'locked in.' Add ~5lb next time."
    },
    {
      "date": "2026-06-14",
      "kind": "receipt",
      "tag": "alive",
      "title": "active-rest / regulation day #2",
      "body": "11.7k steps + unstructured time with Chris = continued nervous-system downshift across the weekend. Receipt of ."
    },
    {
      "date": "2026-06-14",
      "kind": "knowing",
      "tag": "alive",
      "title": "literally living my life frfr",
      "body": "girls, shopping, a massage, the Knicks, coffee with Chris. a whole weekend of just *being here* for it. this isn't a detour from the work — this IS the work. this is the her you're getting back."
    },
    {
      "date": "2026-06-13",
      "kind": "receipt",
      "tag": "alive",
      "title": "active-rest / regulation day",
      "body": "14k steps + massage + social = legit nervous-system downshift. Counts on its own, not a training gap. Receipt of the present/connected self ()."
    },
    {
      "date": "2026-06-11",
      "kind": "receipt",
      "tag": "strength",
      "title": "goblet/sumo 40 locked",
      "body": "Both cashed clean (goblet 10/10/10, sumo 12/10/10). The long-parked bump is done. New working weight 40 on both. Build toward 12 reps before next bump."
    },
    {
      "date": "2026-06-11",
      "kind": "strength",
      "tag": "strength",
      "title": "stronger than last time",
      "body": "goblet squat: 35 lb → 40 lb"
    },
    {
      "date": "2026-06-11",
      "kind": "strength",
      "tag": "strength",
      "title": "stronger than last time",
      "body": "sumo squat: 35 lb → 40 lb"
    },
    {
      "date": "2026-06-11",
      "kind": "strength",
      "tag": "strength",
      "title": "stronger than last time",
      "body": "overhead press: 20 lb → 25 lb"
    },
    {
      "date": "2026-06-10",
      "kind": "receipt",
      "tag": "responsive",
      "title": "hrv vault 37->87 overnight",
      "body": "Second documented bounce (after 5/31 36->116). Followed a clean controlled session + early bedtime + 8.75hr sleep. Receipt that low morning HRV != depletion when she feels good. Reinforces ."
    },
    {
      "date": "2026-06-09",
      "kind": "receipt",
      "tag": "growth",
      "title": "goblet/sumo 40 greenlit",
      "body": "35lb 12/12/12 x3 rounds with controlled RPE-7 effort = the clean confirmation session that was queued from 6/2 and 6/4. Bump both 35->40 on the NEXT fresh lower day, regardless of readiness tier. No more holding."
    },
    {
      "date": "2026-06-09",
      "kind": "receipt",
      "tag": "strength",
      "title": "leg curl new working weight 50",
      "body": "Self-progressed 40(easy)->50x8x2. New working weight 50 lb, established at 8 reps. Build 50 toward 12 reps before adding load. Lumbar-safe RDL sub."
    },
    {
      "date": "2026-06-09",
      "kind": "strength",
      "tag": "strength",
      "title": "stronger than last time",
      "body": "leg curl: 40 lb → 50 lb"
    },
    {
      "date": "2026-06-08",
      "kind": "receipt",
      "tag": "strength",
      "title": "lat pulldown 75 confirmed as ceiling",
      "body": "10/9/5+3 (broken final set). Hold 75, bank clean reps — do NOT add load/reps. Final set exceeded RPE-7 cap but at a held weight (volume note, not a PR)."
    },
    {
      "date": "2026-06-08",
      "kind": "strength",
      "tag": "strength",
      "title": "stronger than last time",
      "body": "lat pulldown: 75 lb (provisional, 6/4) → 75 lb (confirmed ceiling, 6/8)"
    },
    {
      "date": "2026-06-08",
      "kind": "knowing",
      "tag": "growth",
      "title": "you let yourself just *want* it",
      "body": "you said it plain: the hourglass, the abs — you've always wanted that, and you're done apologizing for wanting it. wanting what you want, without the guilt tax, is its own kind of free."
    },
    {
      "date": "2026-06-07",
      "kind": "receipt",
      "tag": "alive",
      "title": "full rest by choice",
      "body": "Appropriate recovery after a big-volume weekend. Good self-regulation, not avoidance."
    },
    {
      "date": "2026-06-06",
      "kind": "receipt",
      "tag": "alive",
      "title": "restorative day, on-values",
      "body": "~20k steps of unstructured city walking + massage + acupuncture. Active recovery + nervous-system care, exactly the regulated/present version of herself the system targets. Not a session to optimize — to celebrate."
    },
    {
      "date": "2026-06-05",
      "kind": "responsive",
      "tag": "responsive",
      "title": "a responsive body",
      "body": "HRV 127 — your nervous system voting 'i'm here, i answer.'"
    },
    {
      "date": "2026-06-05",
      "kind": "knowing",
      "tag": "growth",
      "title": "you started asking the braver questions",
      "body": "you started asking, out loud, whether you'd been too hard on yourself for a long time — and whether you deserved gentler. asking is the brave part. you're not running from the question anymore."
    },
    {
      "date": "2026-06-04",
      "kind": "receipt",
      "tag": "alive",
      "title": "lat pulldown progressed 65->75",
      "body": "New working weight 75 lb (10/8/8). Stack has no 70 (steps 60/65/75) so the jump was forced larger than planned. Round 3 near-failure (RPE ~9-10). Round 1 used an easier-grip attachment. CONSOLIDATE at 75 + standardize the attachment for 1-2 sessions before adding reps/load. Do NOT bump again off this."
    },
    {
      "date": "2026-06-04",
      "kind": "receipt",
      "tag": "growth",
      "title": "high day earned via sleep",
      "body": "8.5hr after the 6/3 short night flipped readiness MODERATE->HIGH. Direct receipt that the recovery-day + sleep call paid off."
    },
    {
      "date": "2026-06-04",
      "kind": "strength",
      "tag": "strength",
      "title": "stronger than last time",
      "body": "lat pulldown: 65 lb → 75 lb"
    },
    {
      "date": "2026-06-04",
      "kind": "knowing",
      "tag": "strength",
      "title": "lat pulldown → 75",
      "body": "you climbed the whole stack — 60 to 75. that's not the machine being nice to you. that's you, stronger than you were. a number that only goes one direction when you keep showing up."
    },
    {
      "date": "2026-06-03",
      "kind": "receipt",
      "tag": "growth",
      "title": "clean zone 2",
      "body": "avg 110 / peak 123 over 63.5 min — held aerobic the whole hour, no spikes. Exactly the recovery-day target."
    },
    {
      "date": "2026-06-01",
      "kind": "receipt",
      "tag": "growth",
      "title": "back to lifting",
      "body": "First strength session after a full week of LOW/active-recovery. MODERATE read held up — executed cleanly, felt fine, no symptom return."
    },
    {
      "date": "2026-05-31",
      "kind": "receipt",
      "tag": "responsive",
      "title": "massive hrv bounce (3.2x)",
      "body": "36 -> 116 in 24hr after real rest day. Body is responsive — was depleted, not broken."
    },
    {
      "date": "2026-05-31",
      "kind": "receipt",
      "tag": "alive",
      "title": "real-time audit practice",
      "body": "Walked coach through her own decision tree openly. The noticing CAPACITY is online; the chain catch is still downstream. Next iteration: catch the body-energy vs caffeine-energy question before the shoes go on."
    },
    {
      "date": "2026-05-31",
      "kind": "responsive",
      "tag": "responsive",
      "title": "a responsive body",
      "body": "HRV 116 — your nervous system voting 'i'm here, i answer.'"
    },
    {
      "date": "2026-05-31",
      "kind": "knowing",
      "tag": "responsive",
      "title": "your body bounced back in a single day",
      "body": "HRV vaulted 36 → 116 overnight — after rest, fuel, Chris, a nap, a walk. that's a body voting *responsive*, loud and clear. receipt against the 'i broke it' story: you didn't. it answers when you're good to it."
    },
    {
      "date": "2026-05-30",
      "kind": "knowing",
      "tag": "growth",
      "title": "you said the hardest thing out loud",
      "body": "you named the bargain you'd been living inside for years — out loud, to someone. that's not the small thing. naming it is the first move of walking out of it. that took more than any lift."
    },
    {
      "date": "2026-05-29",
      "kind": "receipt",
      "tag": "growth",
      "title": "small win on morning pattern (reported next day)",
      "body": "User reported 'brain woke a lil work but not as much' on 5/30 — modest softening. Lever may be landing."
    },
    {
      "date": "2026-05-28",
      "kind": "receipt",
      "tag": "alive",
      "title": "executed the outdoor-with-chris walk",
      "body": "PM Central Park walk hit the parasympathetic criteria (outdoor, companion, no work). Not consolation — active regulation work."
    },
    {
      "date": "2026-05-27",
      "kind": "receipt",
      "tag": "responsive",
      "title": "accepted the recovery day",
      "body": "Initial instinct was to push upper 'to absorb the debt.' After coach surfaced the reschedule rule (LOW doesn't absorb), she accepted. Real contrast to Monday's HRV-43 day when she ran against the LOW call. Self-awareness intact today."
    },
    {
      "date": "2026-05-27",
      "kind": "receipt",
      "tag": "alive",
      "title": "clean zone 1/2 walk",
      "body": "Avg HR 81, peak 108, 45min. True recovery effort, no creep into higher zones. Walk-only protocol honored."
    },
    {
      "date": "2026-05-26",
      "kind": "receipt",
      "tag": "responsive",
      "title": "hrv recovered",
      "body": "43 (Mon, -3.1 SD) -> 81 (at/above rolling baseline). Autonomic system cleared the crash overnight. Full session appropriate; not over-cautioned."
    },
    {
      "date": "2026-05-26",
      "kind": "receipt",
      "tag": "growth",
      "title": "core volume up, breath-led",
      "body": "3 full rounds of dead bug + stomach vacuum + side plank/dips. Her preferred regulating style. Good for a hot nervous system. Vacuum was passive breathing today vs the deep pelvic-floor moment of 5/19."
    },
    {
      "date": "2026-05-25",
      "kind": "receipt",
      "tag": "growth",
      "title": "hrr 33 strong",
      "body": "Cardiovascular fitness intact across the 5-day streak."
    },
    {
      "date": "2026-05-24",
      "kind": "receipt",
      "tag": "growth",
      "title": "hrr 46 strong",
      "body": "Cardiovascular fitness intact across the streak."
    },
    {
      "date": "2026-05-24",
      "kind": "responsive",
      "tag": "responsive",
      "title": "a responsive body",
      "body": "HRV 120 — your nervous system voting 'i'm here, i answer.'"
    },
    {
      "date": "2026-05-23",
      "kind": "receipt",
      "tag": "responsive",
      "title": "hrr solid despite low hrv",
      "body": "37 bpm drop in first minute is healthy. Cardiovascular fitness is intact. Issue is autonomic load, not the heart."
    },
    {
      "date": "2026-05-20",
      "kind": "responsive",
      "tag": "responsive",
      "title": "a responsive body",
      "body": "HRV 117 — your nervous system voting 'i'm here, i answer.'"
    },
    {
      "date": "2026-05-19",
      "kind": "receipt",
      "tag": "growth",
      "title": "pelvic-floor / breath-led core landed",
      "body": "Stomach vacuum became a multi-minute diaphragm-led moment. Tied to broader gut/pelvic context. Going forward: include at least one breath-led or pelvic-floor-aware slot in Tue/Thu core circuits. See feedback_core_preference.md (updated 5/19)."
    },
    {
      "date": "2026-05-19",
      "kind": "receipt",
      "tag": "growth",
      "title": "user wants more",
      "body": "Glute bridge holds, side leg raises, pilates/yoga-adjacent functional work. Weave into rotation."
    },
    {
      "date": "2026-05-19",
      "kind": "responsive",
      "tag": "responsive",
      "title": "a responsive body",
      "body": "HRV 134 — your nervous system voting 'i'm here, i answer.'"
    },
    {
      "date": "2026-05-18",
      "kind": "receipt",
      "tag": "growth",
      "title": "adaptive",
      "body": "Improvised a sensible session without coaching — upper compound + autoregulated core/mobility based on what body asked for."
    },
    {
      "date": "2026-05-15",
      "kind": "receipt",
      "tag": "responsive",
      "title": "body absorbed",
      "body": "HRR 30, HRV 81 pre = had resources, used them, no autonomic cost visible today."
    },
    {
      "date": "2026-05-15",
      "kind": "receipt",
      "tag": "responsive",
      "title": "hrv/rhr stable",
      "body": "No autonomic flag from today's session. HRV 81 going in, RHR steady. Body is handling the volume + intensity at this dose."
    },
    {
      "date": "2026-05-14",
      "kind": "receipt",
      "tag": "growth",
      "title": "rest discipline",
      "body": "2 min between rounds preserved rep counts across all main exercises. Pattern locked in."
    },
    {
      "date": "2026-05-14",
      "kind": "receipt",
      "tag": "strength",
      "title": "hip thrust clean",
      "body": "3×15 at 50 lb, no notes of struggle. Working weight stable."
    },
    {
      "date": "2026-05-12",
      "kind": "receipt",
      "tag": "strength",
      "title": "leg curl 40 lb at pf",
      "body": "New working weight point. Track as PF leg curl, don't conflate with any home alternative."
    },
    {
      "date": "2026-05-12",
      "kind": "receipt",
      "tag": "alive",
      "title": "autoregulation",
      "body": "RDL set 3 skipped intelligently. Not 'gave up' — recognized form issue and stopped. Right call."
    },
    {
      "date": "2026-05-11",
      "kind": "receipt",
      "tag": "strength",
      "title": "lat pulldown 65 consolidated again",
      "body": "2x12 clean. Three sessions at 65 now (Apr 30 PR, May 7, May 11). 70 retest cleared for next HIGH-tier strength day."
    },
    {
      "date": "2026-05-11",
      "kind": "receipt",
      "tag": "strength",
      "title": "rest discipline",
      "body": "2 min between rounds = OHP set 2 came back to 10 after 'harder at 8'. Coaching call validated again."
    },
    {
      "date": "2026-05-11",
      "kind": "receipt",
      "tag": "strength",
      "title": "deploy win",
      "body": "Pallof removed from oblique pool today; bicycle crunch + side plank hip dip + stomach vacuum returned as core. Working weight for lat pulldown also updated. System now reflects truth, not just memory."
    },
    {
      "date": "2026-05-08",
      "kind": "receipt",
      "tag": "alive",
      "title": "self-directed friday",
      "body": "Tiffany correctly read MODERATE-day prescription (walking, not intervals) and adapted to real-world commute. No coaching required."
    },
    {
      "date": "2026-05-07",
      "kind": "receipt",
      "tag": "strength",
      "title": "rest discipline worked",
      "body": "2 min between rounds today held OHP at 10 reps every set vs Mon where 60s rest dropped set 2 to 8. Coaching call validated by data."
    },
    {
      "date": "2026-05-07",
      "kind": "receipt",
      "tag": "alive",
      "title": "presence",
      "body": "Genuine engagement, not autopilot. 'Wanted to give up at 7 but pushed' (twice), 'crap i gotta do this two more times' = present with the work even when it was hard. Real shift from late-Apr autopilot pattern."
    },
    {
      "date": "2026-05-07",
      "kind": "receipt",
      "tag": "growth",
      "title": "hrr athletic",
      "body": "Off-peak HRR 34 (strength) and 31/52 (core) are well-conditioned. End-of-session 8 was soft but explainable by movement during cooldown."
    },
    {
      "date": "2026-05-06",
      "kind": "receipt",
      "tag": "responsive",
      "title": "exceptional hrv",
      "body": "100ms = +2.5 SD above baseline. Indicates restoration is working — what's been delivering: weekend rest + Sunday Central Park walk + Mon HIGH session + Tue MODERATE-trimmed session + sleep consistency."
    },
    {
      "date": "2026-05-06",
      "kind": "receipt",
      "tag": "growth",
      "title": "zone targeting correct",
      "body": "Z1/Z2 boundary is the right target for active recovery, not deeper Z2. Phone agent's 'bump incline' suggestion was off — that would push into stimulus-zone, not recovery-zone."
    },
    {
      "date": "2026-05-05",
      "kind": "receipt",
      "tag": "alive",
      "title": "smart autoregulation",
      "body": "Tricep dip drop 20→15 lb for better control = exactly the right move when first set was off. Self-adjustment without grinding. Good."
    },
    {
      "date": "2026-05-05",
      "kind": "receipt",
      "tag": "strength",
      "title": "warmup treadmill confirmed",
      "body": "10 min @ avg 114 = clean Z2. Pattern locking in. Backfilled Mon log to note same modality (Tiffany said elliptical originally, was actually treadmill)."
    },
    {
      "date": "2026-05-04",
      "kind": "receipt",
      "tag": "alive",
      "title": "warmup hr fixed",
      "body": "First warmup at proper Z2 (avg 113) vs. prior 'follows momentum' elliptical pattern (avg 165+). Whether by mode mismatch or actually walking easier, the outcome was right."
    },
    {
      "date": "2026-05-04",
      "kind": "receipt",
      "tag": "growth",
      "title": "hrr athletic",
      "body": "39 bpm at 1 min off peak 186 = athletic range. Body adapting well to programming."
    },
    {
      "date": "2026-05-04",
      "kind": "receipt",
      "tag": "strength",
      "title": "lat pulldown 65 consolidating",
      "body": "2 sets at 65 (set 3 equipment skip). 65 is now the working weight — stable across Thu + today. Working_weights.json file still says '60 lb (retest 65)' — needs update to '65 lb (locked)'."
    },
    {
      "date": "2026-05-04",
      "kind": "receipt",
      "tag": "growth",
      "title": "presence progress",
      "body": "'Both ig — I think I was in it' is partial presence. Vs. April 27-28 ('going through the motions' both days). Real shift, not framing."
    },
    {
      "date": "2026-05-02",
      "kind": "receipt",
      "tag": "alive",
      "title": "on-values movement",
      "body": "Central Park walking maps directly to user_what_matters.md ('slow, appreciative, exploring, going out'). Logging because it's the kind of thing the system should reinforce."
    },
    {
      "date": "2026-05-02",
      "kind": "receipt",
      "tag": "alive",
      "title": "recovery choice",
      "body": "Skipped optional cardio in favor of incidental walking. Right call given week's volume + DOMS."
    },
    {
      "date": "2026-05-01",
      "kind": "receipt",
      "tag": "responsive",
      "title": "body absorbed",
      "body": "HRV 96 pre, HRR 38 1-min post = well-conditioned response. Compare Apr 25 (HRV 72, HRR 12) where same workout shape had very different cost. Different physiology, different read."
    },
    {
      "date": "2026-04-20",
      "kind": "responsive",
      "tag": "responsive",
      "title": "a responsive body",
      "body": "HRV 135 — your nervous system voting 'i'm here, i answer.'"
    },
    {
      "date": "2026-03-16",
      "kind": "responsive",
      "tag": "responsive",
      "title": "a responsive body",
      "body": "HRV 114 — your nervous system voting 'i'm here, i answer.'"
    }
  ],
  "stats": {
    "sessions_logged": 97,
    "moments": 92,
    "hrv_low": 32,
    "hrv_high": 140,
    "since": "2026-03-05"
  },
  "generated_at": "2026-06-24T20:49:24"
};
